### PR TITLE
Ggodlewski patch 4

### LINKED ISSUE #41: AI Navigation side menu not working
The document "AI Chat Box" was published and I can search and locate it in the online help:

image

However, if I use the Navigation bar, I am not able to go to the document and I am redirected back to the starting online help page.

image

I am able to navigate to other documents in other sections.

### PR DESCRIPTION
**Pull request by ggodlewski**
Should fix https://github.com/mieweb/docs/issues/41

### CODE REVIEW

**Comment by monpie3** [comment]
image
https://github.com/mieweb/docs/actions/runs/11385398701/job/31675155869
I checked the build, and it seems there's still an issue (?) 

I wanted to test it on the demo in Cloudflare Pages, but it looks like we broke the navigation along the way - it doesn't appear in my PR either 😅 .

**Review by monpie3 — CHANGES_REQUESTED** [review]
Could you please look into the issues mentioned? I think the issue with the navigation links is still visible in the build logs.

File: navigation2menu.js [hunk 1]
```diff
@@ -18,7 +18,8 @@ for (const line of markdown.split('\n')) {
         continue;
     }
     const indentPart = line.replace(/(^ *\* ).*/, '$1');
-    const markdownLink = line.substring(indentPart.length);
+    const markdownLink = line.substring(indentPart.length)
+         .replace(/#.*$/, '');
     const matched = markdownLink.match(/\[([^\]]+)\]\(([^)]+)\)/);
```
Comment (monpie3) [inline navigation2menu.js]: Btw., just a suggestion, but maybe we could extract this into a new function and add some tests for it? I've had a hard time with regex lately, and it would be great to have some tests as a safety net if we need to make changes in the future.

**Review by monpie3 — APPROVED** [review]
Tested on https://docs-qa.med-web.com/45-merge/ Looks good 👍
